---
author:
title: "EDAV Fall 2019 PSet 5, part A"
output: pdf_document

---
```{r, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)
```

This assignment is designed to help you get started on the final project. Be sure to review the final project instructions (https://edav.info/project.html), in particular the new section on reproducible workflow (https://edav.info/project.html#reproducible-workflow), which summarizes principles that we've discussed in class.
    
### 1. The Team

[2 points]

a) Who's on the team? (Include names and UNIs)
Bangwei Zhou (bz2280)
Zhihao Ai (za2272)

b) How do you plan to divide up the work? (Grading is on a group basis. The point of asking is to encourage you to think about this.)
Right now we are working with four museum datasets (MOMA, MET, Tate, and Carnegie). Thus, at this state, we are each working with two museum datasets, splitting the work equally. After we finishes the preliminary exploratory analysis on the museum datasets (artists and artworks), we will then discuss what other correlations we might want to explore. And by that point, since we will be "merging" all the datasets, we might split the work again by different charts rather than museums per say. Through this way, we think we each get equal amount of work on this project, and made equal contribution to the project, and this project will also be a result of collective effort.

### 2. The Questions

[6 points]

List three questions that you hope you will be able to answer from your research.

Since we are working with datasets and topics that we really don't know what we can find out; thus, we are crafting our "final questions" while exploring the data. Right now, we are thinking to explore and potentially answer the following three questions:

a) Can we find any trend (by museum or across all museums) of collection acquisition? Do they go out during similar years? Or different museums have different preferred years (and the year gaps) to acquire art pieces?

b) Can we find any preference/trend on the medium (by museum or across all museums) by the pieces they collected? (This will require some work of cleaning the data)

c) Are the museums we explored fair instuitions? As in, in the process of collecting pieces, were they generally fair in terms of gender distribution, or medium options? Can we generate any insight with additional research with the graphs we have?

### 3. Which output format do you plan to use to submit the project? 

[2 points]

(You don't have to use the same format for this assignment -- PSet 5, part A -- and the final project itself.)

Choices are:

pdf_document  

html_document  

bookdown book: https://bookdown.org/yihui/bookdown/

shiny app: https://shiny.rstudio.com/  

Our output formwat will be html_document.

(Remember that it's ok to have pieces of the project that don't fit into the chosen output format; in those cases you can provide links to the relevant material.)

### 4. The Data

What is your data source?  What is your method for importing data? Please be specific. Provide relevant information such as any obstacles you're encountering and what you plan to do to overcome them.

[5 points]

Our data sources are all the primary, i.e., the official data sources. Those museums (MOMA, MET, Tate, Carnegie) posted their datasets on their githubs and we imported the data by cloning their repo. One thing we did overcome was working with git lfs. This essential is large files, and we need to first install *git lfs* and *git lfs pull* to get those large files; otherwise, the data won't appear. And they are csv files, so we can work directly with them.

Moving forward, even though we are working with csv files, some columns that we are interested in require some amounts of cleaning. For example, the medium column. One thing that can be very tricky is the fact that how we might want to categorize the mediums. For example, we can have many different items that have similar pattern as in "illustrated book with twenty-two lithographs" and "illustrated book with photogravures" and etc.. In cases like this, do we consider them as the same group of medium? Or not really? We will spend some time to eye-ball those medium and see if there is an accurate to group those medium. In addition, the "grouping" process can also be challenging, as in we need to work with texts.

Similarly, the Acquired Date column also needs some cleaning. Right now, the column is formatted as *year-month-day*, but we might only want to look at years; thus, we also need to extract the year out. That being said, though we have ready-to-use csv files, we still have some dirty cleaning works to do, before we can have clean and beautiful plots produced.

Overall, to clean the datasets we have, there are two primary tasks: first, to decide how we might want to group the "too-detailed" information (such as medium, credit line); and second, to extract the information we wanted. That said, to really complete the first one, we will spend quite amount of time of eye-balling, but then, after we formulate some rules, we can quickly use codes to extract or group the stuff together as we wish.

### 5. Provide a short summary, including 2-3 graphs, of your initial investigations. 

[10 points]

We have some very interesting initial results. From the MOMA datasets, we analyzed the MOMA artist nationality and MOMA artist birth year, as well as the artworks' classification. We analyzed them by looking at their frequency distribution and we plotted the top 5% and 10% of the results to see a high-level trend. Surprisingly, we found out that, even though MOMA is titled as Museum of Modern Art, its significant collections are pieces made by American artists, five times more than the second most frequent nationality (German). That said, maybe "Museum of American Art" can be a better name for MOMA. Besides, we also plotted the Nationality-Frequency bar chart colored by gender. Again, we found out that the male-female ratio is significantly misproportioned. Taking American artists in MOMA as an example, the number of male American artists is three times the number of female American artists (and this is already the best ratio, with other countries, German is 7:1, British is 6:1, Italian is 10:1, and etc.). In other words, MOMA can also be called as the "Museum of Male Art". 

With MOMA artworks, we did a preliminary analysis by their classifications. We discovered that large portion of the pieces are identified as photographs or prints (this is already 5%), if we extend it to top 10%, it only include one more category- illustrated book. If we further extend it to top 50%, we then have more categories (15 categories). But again, we see way more photographs, prints and illustrated books. This haven't told us much yet, but we will do a classification crossing with time, to see if some categories might have low number, but relatively, the growth in that sector is more significant. This will further help us understand MOMA's development in terms of its collection and how the museum positions itself in front of the public. 

