---
title: "Met"
author: "Bangwei Zhou, Zhihao Ai"
date: "12/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(forcats)
library(Hmisc)
library(HH)
library(mi)
# devtools::install_github('CRAN/extracat')
library(extracat)
library(stringr)
library(scales)
```

```{r}
met <- read_csv("../data/raw/met/MetObjects.csv")
met <- met[c('Object ID', 'Department', 'Object Name', 'Title', 'Culture', 'Artist Display Name', 'Artist Nationality', 'Artist Begin Date', 'Artist End Date', 'Object Begin Date', 'Object End Date', 'Medium', 'City', 'Country', 'Classification', 'Tags')]
colnames(met) <- c('ID', 'Department', 'Object Name', 'Object Title', 'Culture', 'Artist Name', 'Artist Nationality', 'Artist Begin Year', 'Artist End Year', 'Object Begin Year', 'Object End Year', 'Medium', 'City', 'Country', 'Classification', 'Tags')
```

```{r}
# overall
met_object_total <- dim(met)[1]
met_object_total
percent(colSums(is.na(met))/met_object_total)
```

```{r}
visna(met, tp = TRUE, sort = 'c')
```


```{r}
# extract the first country name to represent the artist's nationality
met_nationality <- met
met_nationality$`Artist Nationality` <- str_extract(met$`Artist Nationality`, '[[:alpha:]]+')

met_nationality <- met_nationality %>%
  drop_na(`Artist Nationality`) %>%
  group_by(`Artist Nationality`) %>%
  dplyr::summarise(Total = n()) %>%
  mutate(Prop = Total/sum(Total)) %>%
  arrange(Prop) %>%
  ungroup()

ggplot(tail(met_nationality, 10), aes(x=fct_reorder(`Artist Nationality`, Total), y=Total, label=percent(Prop, accuracy = 1))) +
  geom_col(color = mycolor, fill = myfill) + 
  geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  coord_flip() +
  ggtitle("Artist Nationality in Met (top 10)") +
  xlab("Artist Nationality") +
  ylab("Frequency") +
  theme(plot.title = element_text(face = "bold"))
```

```{r}
met_nationality_classification <- met
met_nationality_classification$`Artist Nationality` <- str_extract(met_nationality_classification$`Artist Nationality`, '[[:alpha:]]+')

met_nationality_classification <- met_nationality_classification %>%
  drop_na(`Artist Nationality`, Classification) %>%
  group_by(`Artist Nationality`, Classification) %>%
  dplyr::summarise(Total = n()) %>%
  # mutate(Prop = Total/sum(Total)) %>%
  # arrange(Prop) %>%
  ungroup() %>%
  filter(`Artist Nationality` == 'American') %>%
  arrange(Total)

ggplot(tail(met_nationality_classification, 10), aes(x=fct_reorder(Classification, Total), y=Total)) +
  geom_col(color = mycolor, fill = myfill) + 
  coord_flip() +
  ggtitle("Top 10 Classification by Nationality in Met") +
  xlab("Classification") +
  ylab("Frequency") +
  theme(plot.title = element_text(face = "bold"))
```
```{r}
sort(unique(met_nationality$`Artist Nationality`))
```

